CREATE TABLE public.apitoken
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Auto-incrementing ID
    createdat TIMESTAMP(6) NOT NULL, -- Creation timestamp
    expiresat TIMESTAMP(6), -- Optional expiration timestamp
    token VARCHAR(255) NOT NULL CONSTRAINT uk7dvok5igpwdypbi42651a2vci UNIQUE, -- Unique constraint on token
    description VARCHAR(80)
    user_id BIGINT NOT NULL CONSTRAINT fkhbqydc1s1ntu82388xubojveu REFERENCES public._user -- Foreign key relationship with the user
);

-- Create an explicit index on the "token" column for faster lookups.
CREATE UNIQUE INDEX idx_token ON public.apitoken (token);

ALTER TABLE public.apitoken
    OWNER TO postgres;
