-- liquibase formatted sql

-- changeset tom:create-user-device-table
CREATE TABLE user_device (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token VARCHAR(255) NOT NULL UNIQUE,
    platform VARCHAR(50),
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    last_used TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_user_device_user FOREIGN KEY (user_id) REFERENCES _user(id) ON DELETE CASCADE
);

-- changeset tom:extend-imei-table-geofencing
ALTER TABLE imei ADD COLUMN geofence_center_latitude DOUBLE PRECISION;
ALTER TABLE imei ADD COLUMN geofence_center_longitude DOUBLE PRECISION;
ALTER TABLE imei ADD COLUMN geofence_radius INTEGER;
ALTER TABLE imei ADD COLUMN geofence_active BOOLEAN DEFAULT FALSE;
ALTER TABLE imei ADD COLUMN last_geofence_alert_time TIMESTAMP;
