create table public._user
(
    id        bigint generated by default as identity
        primary key,
    createdat timestamp(6) not null,
    email     varchar(255) not null,
    enabled   boolean      not null,
    password  varchar(255) not null,
    username  varchar(255) not null
        constraint uknlcolwbx8ujaen5h0u2kr2bn2
            unique
);

alter table public._user
    owner to postgres;

create table public.authority
(
    id     bigint generated by default as identity
        primary key,
    name   varchar(255)          not null,
    isrole boolean default false not null
);

alter table public.authority
    owner to postgres;

create table public.user_roles
(
    userid      bigint not null
        constraint user_roles_user_id_fkey
            references public._user
            on delete cascade,
    authorityid bigint not null
        constraint user_roles_authority_id_fkey
            references public.authority
            on delete cascade,
    primary key (userid, authorityid)
);

alter table public.user_roles
    owner to postgres;


