CREATE TABLE users (
                       id bigint generated by default as identity
                           constraint pk_users PRIMARY KEY,
                       username VARCHAR(50) NOT NULL UNIQUE,
                       password VARCHAR(255) NOT NULL,
                       enabled BOOLEAN NOT NULL DEFAULT TRUE,
                       email VARCHAR(160) NOT NULL,
                       createdAt  timestamp(6)

);

CREATE TABLE authorities(
                             id bigint generated by default as identity
                                 constraint pk_roles PRIMARY KEY,
                             username VARCHAR(50) NOT NULL,
                             authority VARCHAR(50) NOT NULL,
                             FOREIGN KEY (username) REFERENCES users (username)
);