CREATE TABLE users (
                       id bigint generated by default as identity
                           constraint pk_users PRIMARY KEY,
                       username VARCHAR(50) NOT NULL UNIQUE,
                       password VARCHAR(255) NOT NULL,
                       enabled BOOLEAN NOT NULL DEFAULT TRUE,
                       email VARCHAR(160) NOT NULL,
                       createdAt  timestamp(6)

);

CREATE TABLE roles(
                             id bigint generated by default as identity
                                 constraint pk_roles PRIMARY KEY,
                             name VARCHAR(50) NOT NULL,
);

CREATE TABLE user_roles (
                            user_id BIGINT NOT NULL,
                            role_id BIGINT NOT NULL,
                            PRIMARY KEY (user_id, role_id),
                            FOREIGN KEY (user_id) REFERENCES users(id),
                            FOREIGN KEY (role_id) REFERENCES roles(id)
);
